# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e53e366caaa89c06a1f97f3d4244bba1d2a586a9a89197f100cf9441de76bd158ac7ce8ae293919f6fb20ca9c68f6c5089b197011ad83328514bbbb9d2a1efe

test:
  secret_key_base: a41af3d1a2b6e03ba8969d1973d4af4b7d68bd3b042a6b21e10bf7da343981290954cc9bc3a5280a594ebb78caadd16271443a84b17dc228a8681ccbee22517b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
